#include "common.h"

void DK(bool &disp, unsigned short int &n, unsigned int &s, double &prec, vector<double> &singleton_bounds, vector<bool> &unsettled, vector<vector<bool>> &A, unsigned short int &iter_DK, unsigned int &piv_DK, double &t_DK, vector<double> &x, vector<double> &excess, double &t1);
void iteration(double &epsi, unsigned int &s, vector<double> &excess, double &prec, unsigned short int &n, vector<vector<bool>> &A, vector<vector<double>>&Arref, vector<bool> &J, vector<bool> &unsettled, unsigned short int &rank, vector<double> &d, vector<double> &x, bool &disp, vector<vector<bool>> &Asettled, unsigned short int &iter_DK, unsigned int &piv_DK, vector<bool> &unsettled_p, vector<double> &singleton_bounds);
void pivot(double &epsi, unsigned int &s, vector<double> &excess, double &prec, unsigned short int &n, vector<vector<bool>> &A, vector<vector<double>>&Arref, vector<bool> &J, vector<bool> &unsettled, unsigned short int &rank, vector<double> &d, vector<double> &x, bool &disp, vector<vector<bool>> &Asettled, bool &piv, unsigned int &t_size, vector<vector<bool>> &Atight, vector<bool> &T, vector<unsigned int> &T_coord, unsigned short int &iter_DK, unsigned int &piv_DK, vector<bool> &unsettled_p, vector<double> &singleton_bounds, vector<vector<bool>> &Atight2, unsigned short int &t2_size, vector<bool> &T2, vector<unsigned int> &T2_coord);
void step(vector<bool> &T, vector<bool> &unsettled, unsigned int &s, vector<vector<bool>> &A, double &epsi, vector<double>&excess, vector<double> &d, unsigned short int &n, vector<double> &x, bool &disp, vector<unsigned int> &T_coord, double &prec, vector<vector<bool>> &Atight, unsigned int &t_size, vector<bool> &unsettled_p, vector<double> &singleton_bounds, vector<vector<bool>> &Atight2, unsigned short int &t2_size, vector<bool> &T2, vector<unsigned int> &T2_coord);
void DK_mem(bool &disp, unsigned short int &n, unsigned int &s, double &prec, vector<double> &singleton_bounds, vector<bool> &unsettled, vector<bool> &a, unsigned short int &iter_DK, unsigned int &piv_DK, double &t_DK, vector<double> &x, vector<double> &excess, double &t1);
void iteration_mem(double &epsi, unsigned int &s, vector<double> &excess, double &prec, unsigned short int &n, vector<bool>&a, vector<vector<double>>&Arref, vector<bool> &J, vector<bool> &unsettled, unsigned short int &rank, vector<double> &d, vector<double> &x, bool &disp, vector<vector<bool>> &Asettled, unsigned short int &iter_DK, unsigned int &piv_DK, vector<bool> &unsettled_p, vector<double> &singleton_bounds);
void pivot_mem(double &epsi, unsigned int &s, vector<double> &excess, double &prec, unsigned short int &n, vector<bool>&a, vector<vector<double>>&Arref, vector<bool> &J, vector<bool> &unsettled, unsigned short int &rank, vector<double> &d, vector<double> &x, bool &disp, vector<vector<bool>> &Asettled, bool &piv, unsigned int &t_size, vector<vector<bool>> &Atight, vector<bool> &T, vector<unsigned int> &T_coord, unsigned short int &iter_DK, unsigned int &piv_DK, vector<bool> &unsettled_p, vector<double> &singleton_bounds, vector<vector<bool>> &Atight2, unsigned short int &t2_size, vector<bool> &T2, vector<unsigned int> &T2_coord);
void step_mem(vector<bool> &T, vector<bool> &unsettled, unsigned int &s, vector<bool> &a, double &epsi, vector<double>&excess, vector<double> &d, unsigned short int &n, vector<double> &x, bool &disp, vector<unsigned int> &T_coord, double &prec, vector<vector<bool>> &Atight, unsigned int &t_size, vector<bool> &unsettled_p, vector<double> &singleton_bounds, vector<vector<bool>> &Atight2, unsigned short int &t2_size, vector<bool> &T2, vector<unsigned int> &T2_coord);
void imprdir(vector<double>&d, unsigned short int &n, unsigned int &t_size, vector<vector<bool>> &Atight, unsigned short int &rank, vector<vector<bool>>&Asettled, bool &disp, unsigned short int &t2_size, vector<vector<bool>> &Atight2);
void vec_min(double&m, vector<double>&x);