#include "common.h"

void SD(bool &disp, unsigned short int &n, unsigned int &s, vector<double> &v, unsigned short int &iter, unsigned int &piv, double &t, vector<double> &x, bool &nlsu);
void iteration(vector<bool> &unsettled, vector<unsigned int> &settled, unsigned int &s, unsigned short int &n, vector<vector<bool>> &A, vector<double> &x, vector<double> &v, double &epsi, double &prec, vector<vector<double>> &Arref, vector<bool> &J, unsigned short int &rank, bool &disp, IloModel &model, IloNumVarArray &Lambda, IloExpr &obj, IloCplex &lp, IloEnv &env, vector<double>&u, IloObjective &OBJ, IloExpr &pos_eq, IloConstraint &pos, IloRangeArray &balanced, IloExprArray &bal_eq, unsigned short int &iter, unsigned int &piv, vector<bool> &unsettled_p, IloNumVarArray &Lambda_impu, vector<double> &u_impu, vector<double> &singleton_bounds, vector<double> &settled_values, bool &nlsu);
void SD_sg(bool &disp, unsigned short int &n, unsigned int &s, vector<bool> &v, unsigned short int &iter, unsigned int &piv, double &t, vector<double> &x, bool &nlsu);
void iteration_sg(vector<bool> &unsettled, vector<unsigned int> &settled, unsigned int &s, unsigned short int &n, vector<vector<bool>> &A, vector<double> &x, vector<bool> &v, double &epsi, double &prec, vector<vector<double>> &Arref, vector<bool> &J, unsigned short int &rank, bool &disp, IloModel &model, IloNumVarArray &Lambda, IloExpr &obj, IloCplex &lp, IloEnv &env, vector<double>&u, IloObjective &OBJ, IloExpr &pos_eq, IloConstraint &pos, IloRangeArray &balanced, IloExprArray &bal_eq, unsigned short int &iter, unsigned int &piv, vector<bool> &unsettled_p, IloNumVarArray &Lambda_impu, vector<double> &u_impu, vector<double> &singleton_bounds, vector<double> &settled_values, bool &nlsu);
void SD_mem(bool &disp, unsigned short int &n, unsigned int &s, vector<double> &v, unsigned short int &iter, unsigned int &piv, double &t, vector<double> &x, bool &nlsu);
void iteration_mem(vector<bool> &unsettled, vector<unsigned int> &settled, unsigned int &s, unsigned short int &n, vector<bool> &a, vector<double> &x, vector<double> &v, double &epsi, double &prec, vector<vector<double>> &Arref, vector<bool> &J, unsigned short int &rank, bool &disp, IloModel &model, IloNumVarArray &Lambda, IloExpr &obj, IloCplex &lp, IloEnv &env, vector<double>&u, IloObjective &OBJ, IloExpr &pos_eq, IloConstraint &pos, IloRangeArray &balanced, IloExprArray &bal_eq, unsigned short int &iter, unsigned int &piv, vector<bool> &unsettled_p, IloNumVarArray &Lambda_impu, vector<double> &u_impu, vector<double> &singleton_bounds, vector<double> &settled_values, bool &nlsu);
void SD_sg_mem(bool &disp, unsigned short int &n, unsigned int &s, vector<bool> &v, unsigned short int &iter, unsigned int &piv, double &t, vector<double> &x, bool &nlsu);
void iteration_sg_mem(vector<bool> &unsettled, vector<unsigned int> &settled, unsigned int &s, unsigned short int &n, vector<bool> &a, vector<double> &x, vector<bool> &v, double &epsi, double &prec, vector<vector<double>> &Arref, vector<bool> &J, unsigned short int &rank, bool &disp, IloModel &model, IloNumVarArray &Lambda, IloExpr &obj, IloCplex &lp, IloEnv &env, vector<double>&u, IloObjective &OBJ, IloExpr &pos_eq, IloConstraint &pos, IloRangeArray &balanced, IloExprArray &bal_eq, unsigned short int &iter, unsigned int &piv, vector<bool> &unsettled_p, IloNumVarArray &Lambda_impu, vector<double> &u_impu, vector<double> &singleton_bounds, vector<double> &settled_values, bool &nlsu);
